### PR TITLE
Swagger 2.0

### PR DESCRIPTION
**Pull request by gdoumenc**
Reset static folder
Added multi url for resource
Operation may be defined on resource (more parameters on operation decorator)

Checked on python 3.4 only and using no decorator
Can you tell me how to run test and create mines (I don't see any requirements.txt so I cannot test on local.. Is there another way to make py.test running?)

### CODE REVIEW

**Comment by sobolevn** [comment]
Thank you for your help! 

You can run tests with `python setup.py test` or `py.test`. It will be a great thing to do.
Since right now I don't have any time for it. Check this out: https://github.com/flask-restful-swagger/flask-restful-swagger/issues/7

I have already started some tests, but it is just nothing. I would highly appreciate your help!

We also need to think about backwards compatibility. Since the old version has a lot of users. It would be really bad to break everything for now.

**Comment by gdoumenc** [comment]
py.test doesn't work as I need to define the file test -q.. and all 
python modules are not defined (requirement.txt is not defined)
I've tried before asking you help ;) Anyway I will propose something

Normally backward compatibility is preserved!

Le 04/04/2016 20:20, Sobolev Nikita a écrit :

> Thank you for your help!
> 
> You can run tests with |python setup.py test| or |py.test|. It will be 
> a great thing to do.
> Since right now I don't have any time for it. Check this out: #7 
> https://github.com/flask-restful-swagger/flask-restful-swagger/issues/7
> 
> I have already started some tests, but it is just nothing. I would 
> highly appreciate your help!
> 
> We also need to think about backwards compatibility. Since the old 
> version has a lot of users. It would be really bad to break everything 
> for now.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/flask-restful-swagger/flask-restful-swagger/pull/9#issuecomment-205431647

## 

Guillaume DOUMENC
_FPR / CoWorks_
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by sobolevn** [comment]
Does this work for you? https://github.com/flask-restful-swagger/flask-restful-swagger/blob/master/setup.py#L40

And running with `python setup.py test`

**Comment by gdoumenc** [comment]
nope.. no package are installed..?
neither flask..etc.. neither pytest.

I think requirements.txt is missing no?

Le 05/04/2016 09:27, Sobolev Nikita a écrit :

> |python setup.py test|

## 

Guillaume DOUMENC
_FPR / CoWorks_
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by sobolevn** [comment]
`requirements.txt` is an optional file, when using `setup.py`. Have you tried either `python setup.py develop` or `pip install -e .`?

**Comment by gdoumenc** [comment]
Ok I didn't know this setup option (tx) :so I installed all packages 
thru the two commands, bu I still get an error:

(rest)studiogdo@gdo-laptop:~/workspace/rest$ python setup.py test
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
    or: setup.py --help [cmd1 cmd2 ...]
    or: setup.py --help-commands
    or: setup.py cmd --help

error: invalid command 'pytest'
(rest)studiogdo@gdo-laptop:~/workspace/rest$ pip freeze
aniso8601==1.1.0
Flask==0.10.1
Flask-RESTful==0.3.5
-e 
git+git@github.com:gdoumenc/flask-restful-swagger.git@ea6167d409cef6d712971c8c02378638314ab1af#egg=flask_restful_swagger
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
py==1.4.31
pytest==2.9.1
python-dateutil==2.5.2
pytz==2016.3
six==1.10.0
Werkzeug==0.11.5
(rest)studiogdo@gdo-laptop:~/workspace/rest$ py.test

# ============================= test session starts 

platform linux2 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/studiogdo/workspace/rest, inifile:
collected 0 items

# ========================= no tests ran in 0.01 seconds 

Le 05/04/2016 09:32, Sobolev Nikita a écrit :

> |requirements.txt| is an optional file, when using |setup.py|. Have 
> you tried either |python setup.py develop| or |pip install -e .|?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/flask-restful-swagger/flask-restful-swagger/pull/9#issuecomment-205699123

## 

Guillaume DOUMENC
_FPR / CoWorks_
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by gdoumenc** [comment]
By the way I have installed travis account on my github fork and the 
tests succeed.
So I just need the info to make it work locally..
Thanks

Le 05/04/2016 09:32, Sobolev Nikita a écrit :

> |requirements.txt| is an optional file, when using |setup.py|. Have 
> you tried either |python setup.py develop| or |pip install -e .|?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/flask-restful-swagger/flask-restful-swagger/pull/9#issuecomment-205699123

## 

Guillaume DOUMENC
_FPR / CoWorks_
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by gdoumenc** [comment]
Last info :

(rest)studiogdo@gdo-laptop:~/workspace/rest$ py.test -q tests/apps/swg_app.py 
.
1 passed in 0.07 seconds

**Comment by sobolevn** [comment]
I have updated the `setup.py`, and walked through the entire process. https://github.com/flask-restful-swagger/flask-restful-swagger/blob/version-1.0.0/setup.py

What have I done to run the tests:
1. `pip install -e .`
2. `python setup.py test` (with the new test runner it will be fine)

This will launch `py.test` with zero tests collected. Since there are no test-cases inside the `tests` package.

If you will add a simple `test_me.py` module with `def test_smth(): assert 1 == 1`, it will be collected.

**Comment by gdoumenc** [comment]
``` shell
studiogdo@gdo-laptop:~/workspace/rest$ python setup.py test
running pytest
Searching for pytest>=2.9.0
Best match: pytest 2.9.1
Processing pytest-2.9.1-py3.4.egg

Using /home/studiogdo/workspace/rest/.eggs/pytest-2.9.1-py3.4.egg
Searching for py>=1.4.29
Best match: py 1.4.31
Processing py-1.4.31-py3.4.egg

Using /home/studiogdo/workspace/rest/.eggs/py-1.4.31-py3.4.egg
running egg_info
writing flask_restful_swagger.egg-info/PKG-INFO
writing requirements to flask_restful_swagger.egg-info/requires.txt
writing dependency_links to flask_restful_swagger.egg-info/dependency_links.txt
writing top-level names to flask_restful_swagger.egg-info/top_level.txt
reading manifest file 'flask_restful_swagger.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching 'Makefile'
writing manifest file 'flask_restful_swagger.egg-info/SOURCES.txt'
running build_ext
==================================================================== test session starts =====================================================================
platform linux -- Python 3.4.4, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/studiogdo/workspace/rest, inifile: 
collected 0 items 

================================================================ no tests ran in 0.01 seconds ================================================================
s
```

**Comment by sobolevn** [comment]
This is very strange. I will recreate this workflow from scratch and document it. Thanks.

**Pull request closed without merging**
