### PR TITLE
Version 1.0.0

### PR DESCRIPTION
**Pull request by gdoumenc**
Using swagger V2.0
TAG added
Operations can be defined in MRO
Static files removed as version dependant

### CODE REVIEW

**Comment by sobolevn** [comment]
Wow! That's a lot of changes! Thanks for your work.

Could you please squash your commits properly? You are also trying to merge with master instead of `version-1.0.0` branch.

**Comment by gdoumenc** [comment]
I fact no as I'm not happy with the code...

Several reasons we can discuss :
- No test... no comment
- Operation can be defined only as decorator. If using an inherited
  function, as all informations are set on the method (the
  operation)so it doesn't work... As shared methods are often used a
  model API, this is very annoying
- I haven't add the model introspection (from SQLAlchemy) as I did'nt
  know how you wanted to to it... (any specific design request..?)

So I need to discuss more with you about how to make it evolving

Regards

Le 03/04/2016 18:54, Sobolev Nikita a écrit :

> Wow! That's a lot of changes! Thanks for your work.
> 
> Could you please squash your commits properly? You are also trying to 
> merge with master instead of |version-1.0.0| branch.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/flask-restful-swagger/flask-restful-swagger/pull/8#issuecomment-205009195

## 

Guillaume DOUMENC
_FPR / CoWorks_
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by gdoumenc** [comment]
Sorry I created a pull request on root project, not yours.. Let you 
remove it..

Le 03/04/2016 18:54, Sobolev Nikita a écrit :

> Wow! That's a lot of changes! Thanks for your work.
> 
> Could you please squash your commits properly? You are also trying to 
> merge with master instead of |version-1.0.0| branch.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/flask-restful-swagger/flask-restful-swagger/pull/8#issuecomment-205009195

## 

Guillaume DOUMENC
_FPR / CoWorks_
Your Internet Enabler
http://www.fpr-coworks.com

**Comment by sobolevn** [comment]
Closed the root PR. 
1. This is not good, but since we don't have tests at all, this is acceptable (for now).
2. Sorry, I didn't get the idea about your's number 2. Can you please provide code samples?
3. I haven't dig this out yet. It was a good proposal on the main project. I thought that it might be a nice feature to implement, but no rush for this one.
4. About static files. I have used the proper version of the `swagger-ui` which supports both versions of `swagger`'s specs. Were there any issues for you?

**Comment by gdoumenc** [comment]
1. ;)
2. If you define the get method for example by inheritance, the get operation (which will be the same method for all resources) will be used several times. Then adding informations on this method will be overridden by last used. Using decorator, this won't occur as the decorator is set on the root method not on the inherited class...
   Using inherited methods forces to change replacing `resource.origin__.dict__` by `dir(resource.origin)` in:

``` python
def extract_operations(resource):
    operations = []
    for k in dir(resource.orig):
        v = getattr(resource.orig, k)
```
1. At least we should provide import depending on ORM used (as done for swagger version)
2. Not quite sure I got an issue with this... I will check again using your files. Anyway I think we should not provide the static files but write in the doc how to get it from `swagger-ui`.

**Comment by sobolevn** [comment]
Oh, I got it. Thanks for the fix.

I will experiment with ORM and models this week.

I disagree with you about that we should not provide static files at all. My plan was to have a `gitmodule` to contain these files. Also, it is possible to integrate `collectstatics` command to have them in one place. Because why not? If we document how to change them (there are `static_url` and `static_dir` options), how to serve them in production and storing them as a submodule - it is totally fine by me. So it is easy to setup up and test.

**Comment by gdoumenc** [comment]
It is not fixed.. We should provide another implementation for having operation informations on resource not on operation...
Ok for the static files, I will reset. Also good idea you planned to have `gitmodule`..

**Comment by kavink** [comment]
@gdoumenc @sobolevn Question on how Swagger can be used by to pass auth_token or some form of auth in header or as cookies to API server ? And if its possible someone can integrate their own function/module to allow authentication .. So swagger UI can use it ? 

Would be great if its documented.

**Comment by sobolevn** [comment]
With the old version you have to fork-and-customize the code. 

But yes, it is possible with this version. What you have to do is to create your own `swagger-ui` folder and set it with `template_folder` and/or `static_folder`. Se https://github.com/flask-restful-swagger/flask-restful-swagger/blob/version-1.0.0/flask_restful_swagger/swagger.py#L120 and https://github.com/flask-restful-swagger/flask-restful-swagger/blob/version-1.0.0/flask_restful_swagger/producers.py#L48 . We will have this feature documented when the new version will be released.

**Comment by kavink** [comment]
@sbololevn Thanks for the update! ill keep an eye out for the next release and docs

**Pull request closed without merging**
